# -*- coding: utf-8 -*-
"""Numpy Array 1D.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hwB3BgjzKUXy0Jp-beCAcRHcTtuJO5Qj
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install numpy

"""Numpy Array

"""

import numpy as np

numbers1= [1,2,3,4,5,6]
numbers2= [3,5,3,6,7,4]
numbers3= [6,43,45,63,63,34]
numbers4= [64,34,53,24,5,43]
numbers5= [74,46,74,44,45,435]
array1 = np.array(numbers1)
array2 = np.array(numbers2)
array3 = np.array(numbers3)
array4 = np.array(numbers4)
array5 = np.array(numbers5)
print(array1)
print(array2)
print(array3)
print(array4)
print(array5)

print(type(array1))
print(type(array2))
print(type(array3))
print(type(array4))
print(type(array5))

